### If the dataset was generated by a R script, push the script to a server and save its path in the metadata under the column "relation" with name 'script_dataset_generation'

push_R_script_to_server<-function(metadata_and_parameterization,virtual_repository_with_R_files,vre_username,vre_token){

  ## Save the R code with the parameterization for the current dataset
  RFileName<-paste0(metadata_and_parameterization$identifier,".R")
  if(substr(metadata_and_parameterization$path_to_script_dataset_generation,1,4)=="http"){
    download.file(metadata_and_parameterization$path_to_script_dataset_generation,paste0(getwd(),"/",RFileName))
  } else {
    file.copy(from=metadata_and_parameterization$path_to_script_dataset_generation, to=paste0(getwd(),"/",RFileName))
  }
  
  fConn <- file(paste0(getwd(),"/",RFileName), 'r+')
  Lines <- readLines(fConn)
  parameters_columns<-colnames(metadata_and_parameterization)[which(grepl("parameter_",colnames(metadata_and_parameterization)))]
  parameters_with_values<-NULL
  for (i in 1:length(parameters_columns)){
    if (nchar(metadata_and_parameterization[,parameters_columns[i]])>0){
      parameters_with_values<-paste0(parameters_with_values,gsub("parameter_","",parameters_columns[i]),"<-'",metadata_and_parameterization[,parameters_columns[i]],"'\n")
      parameters_with_values<-gsub("'NULL'","NULL",parameters_with_values)
    }
  }
  writeLines(c(paste0("### Parameters \n",parameters_with_values,"\n"), Lines), con = fConn) 
  
  close(fConn)
  
  ## Push R code in the VRE WS
  username<<-vre_username
  token<<-vre_token
  source("http://svn.research-infrastructures.eu/public/d4science/gcube/trunk/data-analysis/RConfiguration/RD4SFunctions/workspace_interaction.r")
  uploadWS(virtual_repository_with_R_files,RFileName,overwrite=T)
  RFileURL <- getPublicFileLinkWS(paste(virtual_repository_with_R_files,RFileName,sep="/"))
  
  ## Add URL to the metadata
  metadata_and_parameterization$relation_script_dataset_generation<-RFileURL
  
  ## remove R script from local
  file.remove(paste0(getwd(),"/",RFileName))

  return(metadata_and_parameterization)  
}
